package com.kkb.pojo;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teach_name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private String teachName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.start_time
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.score
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.hours
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Integer hours;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Course(Integer id, String name, String teachName, Date startTime, Integer score, Integer hours) {
        this.id = id;
        this.name = name;
        this.teachName = teachName;
        this.startTime = startTime;
        this.score = score;
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teach_name
     *
     * @return the value of course.teach_name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public String getTeachName() {
        return teachName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teach_name
     *
     * @param teachName the value for course.teach_name
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setTeachName(String teachName) {
        this.teachName = teachName == null ? null : teachName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.start_time
     *
     * @return the value of course.start_time
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.start_time
     *
     * @param startTime the value for course.start_time
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.score
     *
     * @return the value of course.score
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.score
     *
     * @param score the value for course.score
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.hours
     *
     * @return the value of course.hours
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Integer getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.hours
     *
     * @param hours the value for course.hours
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setHours(Integer hours) {
        this.hours = hours;
    }

    //将Data转为指定格式
    public String getStartTimeText(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(getStartTime());
    }
}