package com.kkb.pojo;

public class SelectCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.u_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.c_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    private Integer cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_course
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public SelectCourse(Integer uId, Integer cId) {
        this.uId = uId;
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_course
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public SelectCourse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.u_id
     *
     * @return the value of select_course.u_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.u_id
     *
     * @param uId the value for select_course.u_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.c_id
     *
     * @return the value of select_course.c_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.c_id
     *
     * @param cId the value for select_course.c_id
     *
     * @mbg.generated Wed Feb 05 17:04:43 CST 2020
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }
}